# Generated by Django 5.1 on 2024-11-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestPerc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('percent', models.IntegerField()),
                ('cid', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='percentage',
            name='uid',
        ),
        migrations.AddField(
            model_name='percentage',
            name='name',
            field=models.TextField(default='None', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
