# Generated by Django 5.1 on 2024-11-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contestperc_remove_percentage_cid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContestPerc',
        ),
        migrations.DeleteModel(
            name='Percentage',
        ),
    ]
