# Generated by Django 5.1 on 2024-11-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_contestperc_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestperc',
            name='link',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
