# Generated by Django 5.1 on 2024-11-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contestperc_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckingDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contestperc',
            name='is_done',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
