# Generated by Django 5.1 on 2024-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_checkingdatas_contestperc_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkingdatas',
            name='ltype',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
